#!/usr/bin/env python3

import sys
import subprocess

def check_factor(number):
    factors_output = subprocess.check_output(['factor', str(number)])
    factors = factors_output.decode().strip().split()[1:]
    factors_array = list(map(int, factors))
    
    if len(factors_array) == 1:
        print(f"{number}=1*{number}")
    else:
        max_factor = factors_array[-1]
        second_max_factor = factors_array[-2]
        
        if len(factors_array) > 2:
            for i in range(len(factors_array) - 3, -1, -1):
                if factors_array[i] * second_max_factor > max_factor * factors_array[i + 1]:
                    break
                second_max_factor = factors_array[i]
        print(f"{number}={max_factor}*{second_max_factor}")


if len(sys.argv) != 2:
    print('Usage: factors.py <file>')
    sys.exit(1)
else:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            number = int(line.strip())
            check_factor(number)
