#!/usr/bin/python3
"""factorize given set of numbers in a file to product of two small numbers"""

from sys import argv


def factorize(number_to_check):
    """"find two small numbers that multiply to give a given number"""
    i = 2

    if num > 239809320265259:
        pass
    if num < 2:
        return

    while num % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(num, num / i, i))


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number_to_check = int(line.split('\n')[0])
            factorize(number_to_check)
            line = file.readline()
except Exception:
    pass
