#!/usr/bin/env python3

import sys
import subprocess

"""Imported the Sys and subprocess module"""


def check_factor(*args):
    """Function to check factors"""
    
    if len(args) != 3:
        num2 = 1
        for i, a in enumerate(args):
            if i > 1:
                num2 *= int(a)
    else:
        num2 = int(args[2])

    num1 = int(args[1])
    num = args[0].replace(':', '=')

    if num2 > num1:
        num1, num2 = num2, num1

    return f'{num}{num1}*{num2}'

if len(sys.argv) != 2:
    print('Usage: rsa <file>')
    sys.exit(1)

with open(sys.argv[1], 'r') as file:
    for line in file:
        result = subprocess.check_output(['factor', line]).decode().strip()
        print(check_factor(*result.split()))
